### ISSUE TITLE
多人并行协作

### ISSUE THREAD

**Issue by muyuqiu001** [oldmanpushcart/greys-anatomy#102]
关于这一条：基于C/S架构的任务模式甚至能让多人同时远程到同一进程上执行不同的指令、脚本，非常适合团队一起进行线上问题排查与跟踪。

通过IP:PORT进行访问报错：
```shell
./greys.sh 85235@101.17.13.16:3659
Exception in thread "main" java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at com.github.ompc.greys.core.GreysConsole.connect(GreysConsole.java:156)
	at com.github.ompc.greys.core.GreysConsole.<init>(GreysConsole.java:67)
	at com.github.ompc.greys.core.GreysConsole.main(GreysConsole.java:274)

````
关于多人并行协作是不是我理解错了：
在17机器上安装了greys，去监控16机器上(16机器上也安装了greys)的85235，然后可以在17机器上进行命令执行。

正确的理解是：
多人都需要通过工具连接到16机器上，然后去运行16机器上的greys

如果下面正确的话那是不是IP就没有必要了？固定为127.0.0.1就可以了呢？

**Comment by oldmanpushcart** [comment]
你没有理解错，但最关键的就是启动网卡要指定，如果没有指定，默认值是`127.0.0.1`网卡才能访问。这个也是出于安全方向考虑。

除非你强制在启动greys的时候指定开放的网卡和端口，否则只有本机可以访问。
