### ISSUE TITLE
在某些特殊的ClassLoader中植入Spy会报错

### ISSUE THREAD

**Issue by oldmanpushcart** [oldmanpushcart/greys-anatomy#112]
在某些特殊的ClassLoader实现中，定义Spy会出现
```
01 2016-01-15 14:09:44.574 WARN [as-command-execute-daemon:arthas] print spy failed. classname=com/alipay/dwsap/web/home/soas/OlapQuery;loader=com.alipay.cloudengine.extensions.equinox.KernelAceClassLoader@2ff1bf46;
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.GeneratedMethodAccessor105.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_33]
        at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_33]
        at com.taobao.arthas.core.util.ArthasReflectUtils.defineClass(ArthasReflectUtils.java:304) ~[arthas-core.jar:na]
        at com.taobao.arthas.core.advisor.Enhancer.spy(Enhancer.java:98) [arthas-core.jar:na]
        at com.taobao.arthas.core.advisor.Enhancer.transform(Enhancer.java:217) [arthas-core.jar:na]
        at sun.instrument.TransformerManager.transform(TransformerManager.java:169) [na:1.6.0_33]
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:365) [na:1.6.0_33]
        at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method) [na:1.6.0_33]
        at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:124) [na:1.6.0_33]
        at com.taobao.arthas.core.advisor.Enhancer.enhance(Enhancer.java:346) [arthas-core.jar:na]
        at com.taobao.arthas.core.command.handler.AbstractCommandHandler.execute(AbstractCommandHandler.java:252) [arthas-core.jar:na]
        at com.taobao.arthas.core.command.handler.DefaultCommandHandler.handleCommand(DefaultCommandHandler.java:67) [arthas-core.jar:na]
        at com.taobao.arthas.core.server.ArthasServer$4.run(ArthasServer.java:276) [arthas-core.jar:na]
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886) [na:1.6.0_33]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908) [na:1.6.0_33]
        at java.lang.Thread.run(Thread.java:662) [na:1.6.0_33]
Caused by: java.lang.LinkageError: loader (instance of  com/alipay/cloudengine/extensions/equinox/KernelAceClassLoader): attempted  duplicate class definition for name: "com/taobao/arthas/core/advisor/Spy"
        at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.6.0_33]
        at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631) ~[na:1.6.0_33]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:615) ~[na:1.6.0_33]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:465) ~[na:1.6.0_33]
        ... 17 common frames omitted
```
这样的错误信息

**Comment by tangweixin** [comment]
请问这是什么ClassLoader?
