### ISSUE TITLE
有没有用过IBM的JDK啊

### ISSUE THREAD

**Issue by muyuqiu001** [oldmanpushcart/greys-anatomy#113]
似乎报错

**Comment by oldmanpushcart** [comment]
没有，能否告知下报错的内容

**Comment by muyuqiu001** [comment]
<pre>
版本：
java version "1.6.0"
Java(TM) SE Runtime Environment (build pxa6460sr16fp4-20150414_01(SR16 FP4))
IBM J9 VM (build 2.4, JRE 1.6.0 IBM J9 2.4 Linux amd64-64 jvmxa6460sr16fp4-20150406_242976 (JIT enabled, AOT enabled)
J9VM - 20150406_242976
JIT  - r9_20150402_88984
GC   - GA24_Java6_SR16_20150406_1410_B242976)
JCL  - 20150413_01
</pre>
报错：
````shell
启动的时候：
Exception in thread "Attachment 32943" java.lang.UnsupportedOperationException: cannot get the capability, performing dispose of the retransforming environment
	at com.ibm.tools.attach.javaSE.Attachment.loadAgentLibraryImpl(Native Method)
	at com.ibm.tools.attach.javaSE.Attachment.loadAgentLibrary(Attachment.java:252)
	at com.ibm.tools.attach.javaSE.Attachment.parseLoadAgent(Attachment.java:230)
	at com.ibm.tools.attach.javaSE.Attachment.doCommand(Attachment.java:140)
	at com.ibm.tools.attach.javaSE.Attachment.run(Attachment.java:101)
进行类增强的时候：
Exception in thread "ga-command-execute-daemon" java.lang.UnsupportedOperationException: cannot get the capability, performing dispose of the retransforming environment
	at sun.instrument.InstrumentationImpl.isRetransformClassesSupported0(Native Method)
	at sun.instrument.InstrumentationImpl.isRetransformClassesSupported(InstrumentationImpl.java:124)
	at sun.instrument.InstrumentationImpl.addTransformer(InstrumentationImpl.java:79)
	at com.github.ompc.greys.core.advisor.Enhancer.enhance(Enhancer.java:402)
	...

Caused by: java.lang.UnsupportedOperationException: adding retransformable transformers is not supported in this environment
	at sun.instrument.InstrumentationImpl.addTransformer(InstrumentationImpl.java:80) ~[na:1.6.0]
	at com.github.ompc.greys.core.advisor.Enhancer.enhance(Enhancer.java:402) ~[greys-core.jar:na]
	at com.github.ompc.greys.core.server.DefaultCommandHandler.execute(DefaultCommandHandler.java:223) ~[greys-core.jar:na]
	... 5 common frames omitted
````


<pre>
版本：
java version "1.8.0"
Java(TM) SE Runtime Environment (build pxa6480sr2-20151023_01(SR2))
IBM J9 VM (build 2.8, JRE 1.8.0 Linux amd64-64 Compressed References 20151019_272764 (JIT enabled, AOT enabled)
J9VM - R28_Java8_SR2_20151019_2144_B272764
JIT  - tr.r14.java_20151006_102517.04
GC   - R28_Java8_SR2_20151019_2144_B272764_CMPRSS
J9CL - 20151019_272764)
JCL - 20151022_01 based on Oracle jdk8u65-b17
</pre>
报错
````Shell
启动的时候：
*** java.lang.instrument ASSERTION FAILED ***: "jvmtierror == JVMTI_ERROR_NOT_AVAILABLE" at JPLISAgent.c line: 1009

执行的进行类增强的时候：
com.github.ompc.greys.core.exception.GaExecuteException: execute failed. sessionId=0
	at com.github.ompc.greys.core.server.DefaultCommandHandler.execute(DefaultCommandHandler.java:281) ~[greys-core.jar:na]
	...

Caused by: java.lang.UnsupportedOperationException: adding retransformable transformers is not supported in this environment
	at sun.instrument.InstrumentationImpl.addTransformer(InstrumentationImpl.java:100) ~[na:1.8.0-internal]
	at com.github.ompc.greys.core.advisor.Enhancer.enhance(Enhancer.java:450) ~[greys-core.jar:na]
	at com.github.ompc.greys.core.server.DefaultCommandHandler.execute(DefaultCommandHandler.java:251) ~[greys-core.jar:na]
	... 5 common frames omitted
````

现在我在调用inst.addTransformer(enhancer, true);之前打印了inst的isRedefineClassesSupported与isRetransformClassesSupported，都为false，还不知道原因

**Comment by oldmanpushcart** [comment]
我今天找到了一台老的Linux 64bit，我安装了IBM的J9，然后...顺利运行了

```
dukun@iZ62un86c7qZ:~$ greys.sh 31714
new version(1.7.3.5) detection, update now...
######################################################################## 100.0%
Archive:  /home/dukun/.greys/lib/temp_1.7.3.5_31855/greys-1.7.3.5-bin.zip
   creating: /home/dukun/.greys/lib/temp_1.7.3.5_31855/greys/
  inflating: /home/dukun/.greys/lib/temp_1.7.3.5_31855/greys/greys-agent.jar  
  inflating: /home/dukun/.greys/lib/temp_1.7.3.5_31855/greys/greys-core.jar  
  inflating: /home/dukun/.greys/lib/temp_1.7.3.5_31855/greys/greys.sh  
  inflating: /home/dukun/.greys/lib/temp_1.7.3.5_31855/greys/install-local.sh  
update completed.
                                                        _                    
  ____  ____ _____ _   _  ___ _____ _____ ____  _____ _| |_ ___  ____  _   _ 
 / _  |/ ___) ___ | | | |/___|_____|____ |  _ \(____ (_   _) _ \|    \| | | |
( (_| | |   | ____| |_| |___ |     / ___ | | | / ___ | | || |_| | | | | |_| |
 \___ |_|   |_____)\__  (___/      \_____|_| |_\_____|  \__)___/|_|_|_|\__  |
(_____|           (____/                                              (____/ 
                                              +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
                                              |v|e|r|s|i|o|n|:|1|.|7|.|3|.|5|
                                              +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
ga?>
ga?>trace *Test print*
Press Ctrl+D to abort.
Affect(class-cnt:1 , method-cnt:2) cost in 304 ms.
`---+Tracing for : thread_name="agent-test-user-printer" thread_id=0xb;is_daemon=false;priority=5;
    `---+[30,30ms]com.alibaba.AgentTest:printUser()
        `---[26,26ms]java.io.PrintStream:println()

`---+Tracing for : thread_name="agent-test-address-printer" thread_id=0xc;is_daemon=false;priority=5;
    `---+[5,5ms]com.alibaba.AgentTest:printAddress()
        +---[3,0ms]com.alibaba.manager.AddressManager:newAddress()
        +---[3,0ms]com.alibaba.manager.AddressManager:toString()
        `---[5,0ms]throw:com.alibaba.AddressException()

`---+Tracing for : thread_name="agent-test-user-printer" thread_id=0xb;is_daemon=false;priority=5;
    `---+[1,1ms]com.alibaba.AgentTest:printUser()
        `---[1,1ms]java.io.PrintStream:println()

`---+Tracing for : thread_name="agent-test-user-printer" thread_id=0xb;is_daemon=false;priority=5;
    `---+[1,0ms]com.alibaba.AgentTest:printUser()
        `---[1,0ms]java.io.PrintStream:println()

`---+Tracing for : thread_name="agent-test-address-printer" thread_id=0xc;is_daemon=false;priority=5;
    `---+[2,1ms]com.alibaba.AgentTest:printAddress()
        +---[1,0ms]com.alibaba.manager.AddressManager:newAddress()
        +---[2,1ms]com.alibaba.manager.AddressManager:toString()
        `---[2,0ms]java.io.PrintStream:println()

`---+Tracing for : thread_name="agent-test-user-printer" thread_id=0xb;is_daemon=false;priority=5;
    `---+[1,1ms]com.alibaba.AgentTest:printUser()
        `---[1,1ms]java.io.PrintStream:println()

`---+Tracing for : thread_name="agent-test-user-printer" thread_id=0xb;is_daemon=false;priority=5;
    `---+[1,1ms]com.alibaba.AgentTest:printUser()
        `---[0,0ms]java.io.PrintStream:println()

`---+Tracing for : thread_name="agent-test-address-printer" thread_id=0xc;is_daemon=false;priority=5;
    `---+[1,1ms]com.alibaba.AgentTest:printAddress()
        +---[0,0ms]com.alibaba.manager.AddressManager:newAddress()
        +---[1,1ms]com.alibaba.manager.AddressManager:toString()
        `---[1,0ms]throw:com.alibaba.AddressException()

ga?>jvm
+--------------------+----------------------------------------------------------------------------------------------------+
|           CATEGORY | INFO                                                                                               |
+--------------------+----------------------------------------------------------------------------------------------------+
|            RUNTIME |              MACHINE-NAME : 31714@iZ62un86c7qZ                                                     |
|                    |            JVM-START-TIME : 2016-01-20 16:26:42                                                    |
|                    |   MANAGEMENT-SPEC-VERSION : 1.0                                                                    |
|                    |                 SPEC-NAME : Java Virtual Machine Specification                                     |
|                    |               SPEC-VENDOR : Sun Microsystems Inc.                                                  |
|                    |              SPEC-VERSION : 1.0                                                                    |
|                    |                   VM-NAME : IBM J9 VM                                                              |
|                    |                 VM-VENDOR : IBM Corporation                                                        |
|                    |                VM-VERSION : 2.4                                                                    |
|                    |           INPUT-ARGUMENTS : -Xjcl:jclscar_24                                                       |
|                    |                             -Dcom.ibm.oti.vm.bootstrap.library.path=/home/dukun/opt/ibm-java-x86_6 |
|                    |                             4-60/jre/lib/amd64/default:/home/dukun/opt/ibm-java-x86_64-60/jre/lib/ |
|                    |                             amd64                                                                  |
|                    |                             -Dsun.boot.library.path=/home/dukun/opt/ibm-java-x86_64-60/jre/lib/amd |
|                    |                             64/default:/home/dukun/opt/ibm-java-x86_64-60/jre/lib/amd64            |
|                    |                             -Djava.library.path=/home/dukun/opt/ibm-java-x86_64-60/jre/lib/amd64/d |
|                    |                             efault:/home/dukun/opt/ibm-java-x86_64-60/jre/lib/amd64:/usr/lib       |
|                    |                             -Djava.home=/home/dukun/opt/ibm-java-x86_64-60/jre                     |
|                    |                             -Djava.ext.dirs=/home/dukun/opt/ibm-java-x86_64-60/jre/lib/ext         |
|                    |                             -Duser.dir=/home/dukun/temp/agent-test                                 |
|                    |                             -Djava.runtime.version=pxa6460sr16fp15-20151106_01 (SR16 FP15)         |
|                    |                             -Xdump                                                                 |
|                    |                             -Djava.class.path=.                                                    |
|                    |                             -Xdebug                                                                |
|                    |                             -Xrunjdwp:transport=dt_socket,address=8787,server=y,suspend=n          |
|                    |                             -Djava.class.path=./target                                             |
|                    |                             -Dsun.java.command=com.alibaba.AgentTest                               |
|                    |                             -Dsun.java.launcher=SUN_STANDARD                                       |
|                    |                             -Dsun.java.launcher.pid=31714                                          |
|                    |                CLASS-PATH : ./target                                                               |
|                    |           BOOT-CLASS-PATH : /home/dukun/opt/ibm-java-x86_64-60/jre/lib/amd64/default/jclSC160/vm.j |
|                    |                             ar:/home/dukun/opt/ibm-java-x86_64-60/jre/lib/annotation.jar:/home/duk |
|                    |                             un/opt/ibm-java-x86_64-60/jre/lib/beans.jar:/home/dukun/opt/ibm-java-x |
|                    |                             86_64-60/jre/lib/java.util.jar:/home/dukun/opt/ibm-java-x86_64-60/jre/ |
|                    |                             lib/jndi.jar:/home/dukun/opt/ibm-java-x86_64-60/jre/lib/logging.jar:/h |
|                    |                             ome/dukun/opt/ibm-java-x86_64-60/jre/lib/security.jar:/home/dukun/opt/ |
|                    |                             ibm-java-x86_64-60/jre/lib/sql.jar:/home/dukun/opt/ibm-java-x86_64-60/ |
|                    |                             jre/lib/ibmorb.jar:/home/dukun/opt/ibm-java-x86_64-60/jre/lib/ibmorbap |
|                    |                             i.jar:/home/dukun/opt/ibm-java-x86_64-60/jre/lib/ibmcfw.jar:/home/duku |
|                    |                             n/opt/ibm-java-x86_64-60/jre/lib/rt.jar:/home/dukun/opt/ibm-java-x86_6 |
|                    |                             4-60/jre/lib/charsets.jar:/home/dukun/opt/ibm-java-x86_64-60/jre/lib/r |
|                    |                             esources.jar:/home/dukun/opt/ibm-java-x86_64-60/jre/lib/ibmpkcs.jar:/h |
|                    |                             ome/dukun/opt/ibm-java-x86_64-60/jre/lib/ibmcertpathfw.jar:/home/dukun |
|                    |                             /opt/ibm-java-x86_64-60/jre/lib/ibmjgssfw.jar:/home/dukun/opt/ibm-java |
|                    |                             -x86_64-60/jre/lib/ibmjssefw.jar:/home/dukun/opt/ibm-java-x86_64-60/jr |
|                    |                             e/lib/ibmsaslfw.jar:/home/dukun/opt/ibm-java-x86_64-60/jre/lib/ibmjcef |
|                    |                             w.jar:/home/dukun/opt/ibm-java-x86_64-60/jre/lib/ibmjgssprovider.jar:/ |
|                    |                             home/dukun/opt/ibm-java-x86_64-60/jre/lib/ibmjsseprovider2.jar:/home/d |
|                    |                             ukun/opt/ibm-java-x86_64-60/jre/lib/ibmcertpathprovider.jar:/home/duku |
|                    |                             n/opt/ibm-java-x86_64-60/jre/lib/management-agent.jar:/home/dukun/opt/ |
|                    |                             ibm-java-x86_64-60/jre/lib/xml.jar:/home/dukun/opt/ibm-java-x86_64-60/ |
|                    |                             jre/lib/jlm.jar:/home/dukun/opt/ibm-java-x86_64-60/jre/lib/javascript. |
|                    |                             jar                                                                    |
|                    |              LIBRARY-PATH : /home/dukun/opt/ibm-java-x86_64-60/jre/lib/amd64/default:/home/dukun/o |
|                    |                             pt/ibm-java-x86_64-60/jre/lib/amd64:/usr/lib                           |
+--------------------+----------------------------------------------------------------------------------------------------+
|      CLASS-LOADING |        LOADED-CLASS-COUNT : 1869                                                                   |
|                    |  TOTAL-LOADED-CLASS-COUNT : 1869                                                                   |
|                    |      UNLOADED-CLASS-COUNT : 0                                                                      |
|                    |                IS-VERBOSE : false                                                                  |
+--------------------+----------------------------------------------------------------------------------------------------+
|        COMPILATION |                      NAME : j9jit24                                                                |
|                    |        TOTAL-COMPILE-TIME : 860(ms)                                                                |
+--------------------+----------------------------------------------------------------------------------------------------+
| GARBAGE-COLLECTORS |          MarkSweepCompact : 8/37(ms)                                                               |
|                    |              [count/time]                                                                          |
+--------------------+----------------------------------------------------------------------------------------------------+
|    MEMORY-MANAGERS |       J9 non-heap manager : class storage                                                          |
|                    |                             JIT code cache                                                         |
|                    |                             JIT data cache                                                         |
|                    |                             miscellaneous non-heap storage                                         |
|                    |          MarkSweepCompact : Java heap                                                              |
+--------------------+----------------------------------------------------------------------------------------------------+
|             MEMORY |         HEAP-MEMORY-USAGE : 4194304/4194304/520331264/4094440                                      |
|                    | [committed/init/max/used]                                                                          |
|                    |      NO-HEAP-MEMORY-USAGE : 41387788/0/-1/31371132                                                 |
|                    | [committed/init/max/used]                                                                          |
|                    |    PENDING-FINALIZE-COUNT : 0                                                                      |
+--------------------+----------------------------------------------------------------------------------------------------+
|   OPERATING-SYSTEM |                        OS : Linux                                                                  |
|                    |                      ARCH : amd64                                                                  |
|                    |          PROCESSORS-COUNT : 1                                                                      |
|                    |              LOAD-AVERAGE : 1.08                                                                   |
|                    |                   VERSION : 3.13.0-32-generic                                                      |
+--------------------+----------------------------------------------------------------------------------------------------+
|             THREAD |                     COUNT : 15                                                                     |
|                    |              DAEMON-COUNT : 11                                                                     |
|                    |                LIVE-COUNT : 15                                                                     |
|                    |             STARTED-COUNT : 18                                                                     |
+--------------------+----------------------------------------------------------------------------------------------------+
Affect cost in 229 ms.
```

所以我比较怀疑你的JVM所跑的参数限制了安全策略，能否给下JVM信息

**Comment by muyuqiu001** [comment]
````shell
ga?>jvm
+--------------------+----------------------------------------------------------------------------------------------------+
|           CATEGORY | INFO                                                                                               |
+--------------------+----------------------------------------------------------------------------------------------------+
|            RUNTIME |              MACHINE-NAME : 29355@02086                                                  |
|                    |            JVM-START-TIME : 2016-01-20 17:16:55                                                    |
|                    |   MANAGEMENT-SPEC-VERSION : 1.0                                                                    |
|                    |                 SPEC-NAME : Java Virtual Machine Specification                                     |
|                    |               SPEC-VENDOR : Sun Microsystems Inc.                                                  |
|                    |              SPEC-VERSION : 1.0                                                                    |
|                    |                   VM-NAME : IBM J9 VM                                                              |
|                    |                 VM-VENDOR : IBM Corporation                                                        |
|                    |                VM-VERSION : 2.4                                                                    |
|                    |           INPUT-ARGUMENTS : -Xjcl:jclscar_24                                                       |
|                    |                             -Dcom.ibm.oti.vm.bootstrap.library.path=/usr/ibm-java-x86_64-60/jre/li |
|                    |                             b/amd64/default:/usr/ibm-java-x86_64-60/jre/lib/amd64                  |
|                    |                             -Dsun.boot.library.path=/usr/ibm-java-x86_64-60/jre/lib/amd64/default: |
|                    |                             /usr/ibm-java-x86_64-60/jre/lib/amd64                                  |
|                    |                             -Djava.library.path=/usr/ibm-java-x86_64-60/jre/lib/amd64/default:/usr |
|                    |                             /ibm-java-x86_64-60/jre/lib/amd64:/usr/lib                             |
|                    |                             -Djava.home=/usr/ibm-java-x86_64-60/jre                                |
|                    |                             -Djava.ext.dirs=/usr/ibm-java-x86_64-60/jre/lib/ext                    |
|                    |                             -Duser.dir=/home/test                                                |
|                    |                             -Djava.runtime.version=pxa6460sr16fp4-20150414_01 (SR16 FP4)           |
|                    |                             -Xdump                                                                 |
|                    |                             -Djava.class.path=.:/usr/ibm-java-x86_64-60/lib/dt.jar:/usr/ibm-java-x |
|                    |                             86_64-60/lib/tools.jar                                                 |
|                    |                             -Djava.class.path=test.jar                                             |
|                    |                             -Dsun.java.command=test.jar 123 1000                                   |
|                    |                             -Dsun.java.launcher=SUN_STANDARD                                       |
|                    |                             -Dsun.java.launcher.pid=29355                                          |
|                    |                CLASS-PATH : test.jar                                                               |
|                    |           BOOT-CLASS-PATH : /usr/ibm-java-x86_64-60/jre/lib/amd64/default/jclSC160/vm.jar:/usr/ibm |
|                    |                             -java-x86_64-60/jre/lib/annotation.jar:/usr/ibm-java-x86_64-60/jre/lib |
|                    |                             /beans.jar:/usr/ibm-java-x86_64-60/jre/lib/java.util.jar:/usr/ibm-java |
|                    |                             -x86_64-60/jre/lib/jndi.jar:/usr/ibm-java-x86_64-60/jre/lib/logging.ja |
|                    |                             r:/usr/ibm-java-x86_64-60/jre/lib/security.jar:/usr/ibm-java-x86_64-60 |
|                    |                             /jre/lib/sql.jar:/usr/ibm-java-x86_64-60/jre/lib/ibmorb.jar:/usr/ibm-j |
|                    |                             ava-x86_64-60/jre/lib/ibmorbapi.jar:/usr/ibm-java-x86_64-60/jre/lib/ib |
|                    |                             mcfw.jar:/usr/ibm-java-x86_64-60/jre/lib/rt.jar:/usr/ibm-java-x86_64-6 |
|                    |                             0/jre/lib/charsets.jar:/usr/ibm-java-x86_64-60/jre/lib/resources.jar:/ |
|                    |                             usr/ibm-java-x86_64-60/jre/lib/ibmpkcs.jar:/usr/ibm-java-x86_64-60/jre |
|                    |                             /lib/ibmcertpathfw.jar:/usr/ibm-java-x86_64-60/jre/lib/ibmjgssfw.jar:/ |
|                    |                             usr/ibm-java-x86_64-60/jre/lib/ibmjssefw.jar:/usr/ibm-java-x86_64-60/j |
|                    |                             re/lib/ibmsaslfw.jar:/usr/ibm-java-x86_64-60/jre/lib/ibmjcefw.jar:/usr |
|                    |                             /ibm-java-x86_64-60/jre/lib/ibmjgssprovider.jar:/usr/ibm-java-x86_64-6 |
|                    |                             0/jre/lib/ibmjsseprovider2.jar:/usr/ibm-java-x86_64-60/jre/lib/ibmcert |
|                    |                             pathprovider.jar:/usr/ibm-java-x86_64-60/jre/lib/management-agent.jar: |
|                    |                             /usr/ibm-java-x86_64-60/jre/lib/xml.jar:/usr/ibm-java-x86_64-60/jre/li |
|                    |                             b/jlm.jar:/usr/ibm-java-x86_64-60/jre/lib/javascript.jar               |
|                    |              LIBRARY-PATH : /usr/ibm-java-x86_64-60/jre/lib/amd64/default:/usr/ibm-java-x86_64-60/ |
|                    |                             jre/lib/amd64:/usr/lib                                                 |
+--------------------+----------------------------------------------------------------------------------------------------+
|      CLASS-LOADING |        LOADED-CLASS-COUNT : 1882                                                                   |
|                    |  TOTAL-LOADED-CLASS-COUNT : 1882                                                                   |
|                    |      UNLOADED-CLASS-COUNT : 0                                                                      |
|                    |                IS-VERBOSE : false                                                                  |
+--------------------+----------------------------------------------------------------------------------------------------+
|        COMPILATION |                      NAME : j9jit24                                                                |
|                    |        TOTAL-COMPILE-TIME : 686(ms)                                                                |
+--------------------+----------------------------------------------------------------------------------------------------+
| GARBAGE-COLLECTORS |          MarkSweepCompact : 11/40(ms)                                                              |
|                    |              [count/time]                                                                          |
+--------------------+----------------------------------------------------------------------------------------------------+
|    MEMORY-MANAGERS |       J9 non-heap manager : class storage                                                          |
|                    |                             JIT code cache                                                         |
|                    |                             JIT data cache                                                         |
|                    |                             miscellaneous non-heap storage                                         |
|                    |          MarkSweepCompact : Java heap                                                              |
+--------------------+----------------------------------------------------------------------------------------------------+
|             MEMORY |         HEAP-MEMORY-USAGE : 6291456/4194304/536870912/6015920                                      |
|                    | [committed/init/max/used]                                                                          |
|                    |      NO-HEAP-MEMORY-USAGE : 28743740/0/-1/17159028                                                 |
|                    | [committed/init/max/used]                                                                          |
|                    |    PENDING-FINALIZE-COUNT : 0                                                                      |
+--------------------+----------------------------------------------------------------------------------------------------+
|   OPERATING-SYSTEM |                        OS : Linux                                                                  |
|                    |                      ARCH : amd64                                                                  |
|                    |          PROCESSORS-COUNT : 4                                                                      |
|                    |              LOAD-AVERAGE : 0.0                                                                    |
|                    |                   VERSION : 2.6.32.59-0.7-default                                                  |
+--------------------+----------------------------------------------------------------------------------------------------+
|             THREAD |                     COUNT : 13                                                                     |
|                    |              DAEMON-COUNT : 12                                                                     |
|                    |                LIVE-COUNT : 13                                                                     |
|                    |             STARTED-COUNT : 15                                                                     |
+--------------------+----------------------------------------------------------------------------------------------------+
Affect cost in 43 ms.
````

**Comment by oldmanpushcart** [comment]
这个启动成功了，那个命令你用不了呢？

**Comment by muyuqiu001** [comment]
启动是能启动成功，但是启动的时候报错，执行命令的时候也会报错，报错就是上面写的那些~

**Comment by oldmanpushcart** [comment]
具体哪些命令？我尝试执行了`trace`，能跑通

**Comment by muyuqiu001** [comment]
就是对类进行加强的这些，比如：
trace stack
````Shell
Exception in thread "Attachment 55383" java.lang.UnsupportedOperationException: cannot get the capability, performing dispose of the retransforming environment
	at com.ibm.tools.attach.javaSE.Attachment.loadAgentLibraryImpl(Native Method)
	at com.ibm.tools.attach.javaSE.Attachment.loadAgentLibrary(Attachment.java:252)
	at com.ibm.tools.attach.javaSE.Attachment.parseLoadAgent(Attachment.java:230)
	at com.ibm.tools.attach.javaSE.Attachment.doCommand(Attachment.java:140)
	at com.ibm.tools.attach.javaSE.Attachment.run(Attachment.java:101)
2016-01-20 17:38:42 [Attachment 55383] INFO  greys-anatomy - ga-server listening on network=127.0.0.1;port=3658;timeout=6000;
MyEvent [myeventid=11, timestamp=1453282722443, id=123]
2016-01-20 17:38:42 [ga-selector-daemon] INFO  greys-anatomy - accept new connection, client=java.nio.channels.SocketChannel[connected local=/127.0.0.1:3658 remote=/127.0.0.1:55966]@session[0]
MyEvent [myeventid=12, timestamp=1453282723443, id=123]
MyEvent [myeventid=13, timestamp=1453282724444, id=123]
MyEvent [myeventid=14, timestamp=1453282725444, id=123]
MyEvent [myeventid=15, timestamp=1453282726444, id=123]
MyEvent [myeventid=16, timestamp=1453282727444, id=123]
MyEvent [myeventid=17, timestamp=1453282728445, id=123]
MyEvent [myeventid=18, timestamp=1453282729445, id=123]
MyEvent [myeventid=19, timestamp=1453282730445, id=123]
Exception in thread "ga-command-execute-daemon" java.lang.UnsupportedOperationException: cannot get the capability, performing dispose of the retransforming environment
	at sun.instrument.InstrumentationImpl.isRetransformClassesSupported0(Native Method)
	at sun.instrument.InstrumentationImpl.isRetransformClassesSupported(InstrumentationImpl.java:124)
	at sun.instrument.InstrumentationImpl.addTransformer(InstrumentationImpl.java:79)
	at com.github.ompc.greys.core.advisor.Enhancer.enhance(Enhancer.java:412)
	at com.github.ompc.greys.core.server.DefaultCommandHandler.execute(DefaultCommandHandler.java:223)
	at com.github.ompc.greys.core.server.DefaultCommandHandler.executeCommand(DefaultCommandHandler.java:87)
	at com.github.ompc.greys.core.server.GaServer$5.run(GaServer.java:356)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:767)
2016-01-20 17:38:50 [ga-command-execute-daemon] WARN  greys-anatomy - command execute failed.
com.github.ompc.greys.core.exception.GaExecuteException: execute failed. sessionId=0
	at com.github.ompc.greys.core.server.DefaultCommandHandler.execute(DefaultCommandHandler.java:254) ~[greys-core.jar:na]
	at com.github.ompc.greys.core.server.DefaultCommandHandler.executeCommand(DefaultCommandHandler.java:87) ~[greys-core.jar:na]
	at com.github.ompc.greys.core.server.GaServer$5.run(GaServer.java:356) [greys-core.jar:na]
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895) [na:1.6.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918) [na:1.6.0]
	at java.lang.Thread.run(Thread.java:767) [na:1.6.0]
Caused by: java.lang.UnsupportedOperationException: adding retransformable transformers is not supported in this environment
	at sun.instrument.InstrumentationImpl.addTransformer(InstrumentationImpl.java:80) ~[na:1.6.0]
	at com.github.ompc.greys.core.advisor.Enhancer.enhance(Enhancer.java:412) ~[greys-core.jar:na]
	at com.github.ompc.greys.core.server.DefaultCommandHandler.execute(DefaultCommandHandler.java:223) ~[greys-core.jar:na]
	... 5 common frames omitted
````
我执行的stack

**Comment by muyuqiu001** [comment]
````shell
*** java.lang.instrument ASSERTION FAILED ***: "jvmtierror == JVMTI_ERROR_NOT_AVAILABLE" at JPLISAgent.c line: 1009
2016-01-20 23:42:19 [Attachment 43403] INFO  greys-anatomy - ga-server listening on network=127.0.0.1;port=3658;timeout=6000;
2016-01-20 23:42:19 [ga-selector-daemon] INFO  greys-anatomy - accept new connection, client=java.nio.channels.SocketChannel[connected local=/127.0.0.1:3658 remote=/127.0.0.1:55676]@session[0]
MyEvent [myid=63] Event [id=563, name=name63]
MyEvent [myid=64] Event [id=564, name=name64]
MyEvent [myid=65] Event [id=565, name=name65]
MyEvent [myid=66] Event [id=566, name=name66]
MyEvent [myid=67] Event [id=567, name=name67]
MyEvent [myid=68] Event [id=568, name=name68]
MyEvent [myid=69] Event [id=569, name=name69]
MyEvent [myid=70] Event [id=570, name=name70]
MyEvent [myid=71] Event [id=571, name=name71]
MyEvent [myid=72] Event [id=572, name=name72]
MyEvent [myid=73] Event [id=573, name=name73]
2016-01-20 23:42:42 [ga-command-execute-daemon] WARN  greys-anatomy - command execute failed.
com.github.ompc.greys.core.exception.GaExecuteException: execute failed. sessionId=0
	at com.github.ompc.greys.core.server.DefaultCommandHandler.execute(DefaultCommandHandler.java:255) ~[greys-core.jar:na]
	at com.github.ompc.greys.core.server.DefaultCommandHandler.executeCommand(DefaultCommandHandler.java:87) ~[greys-core.jar:na]
	at com.github.ompc.greys.core.server.GaServer$4.run(GaServer.java:329) [greys-core.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153) [na:1.8.0-internal]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [na:1.8.0-internal]
	at java.lang.Thread.run(Thread.java:785) [na:1.8.0-internal]
Caused by: java.lang.UnsupportedOperationException: adding retransformable transformers is not supported in this environment
	at sun.instrument.InstrumentationImpl.addTransformer(InstrumentationImpl.java:100) ~[na:1.8.0-internal]
	at com.github.ompc.greys.core.advisor.Enhancer.enhance(Enhancer.java:389) ~[greys-core.jar:na]
	at com.github.ompc.greys.core.server.DefaultCommandHandler.execute(DefaultCommandHandler.java:223) ~[greys-core.jar:na]
	... 5 common frames omitted
MyEvent [myid=74] Event [id=574, name=name74]
MyEvent [myid=75] Event [id=575, name=name75]
^C2016-01-20 23:42:46 [ga-shutdown-hooker] INFO  greys-anatomy - session[0] destroyed.
2016-01-20 23:42:46 [ga-shutdown-hooker] INFO  greys-anatomy - session manager clean completed.
2016-01-20 23:42:46 [ga-shutdown-hooker] INFO  greys-anatomy - session manager destroy completed.
2016-01-20 23:42:46 [ga-shutdown-hooker] INFO  greys-anatomy - ga-server destroy completed.
````
这个是我今晚刚刚装的ubuntu 64位系统与新装的JDK1.8，抛出同样的错误。
````shell
yang@yangs-PC:~$ java -version
java version "1.8.0"
Java(TM) SE Runtime Environment (build pxa6480sr2-20151023_01(SR2))
IBM J9 VM (build 2.8, JRE 1.8.0 Linux amd64-64 Compressed References 20151019_272764 (JIT enabled, AOT enabled)
J9VM - R28_Java8_SR2_20151019_2144_B272764
JIT  - tr.r14.java_20151006_102517.04
GC   - R28_Java8_SR2_20151019_2144_B272764_CMPRSS
J9CL - 20151019_272764)
JCL - 20151022_01 based on Oracle jdk8u65-b17
````

**Comment by oldmanpushcart** [comment]
如果有环境给我登录上去就好了，目前我也只能干着急哎

**Comment by muyuqiu001** [comment]
QQ号能否透露下？可以远程

**Comment by oldmanpushcart** [comment]
QQ：76367959，MAC用户估计很难远程

**Comment by muyuqiu001** [comment]
vmware + Ubuntu15.10 + IBM JDK 1.8 这个环境，MAC上能搭建不？

**Comment by muyuqiu001** [comment]
几经周折，终于找到解决方法了：
在程序启动的时候添加debug参数：
````shell
-Xdebug -Xrunjdwp:transport=dt_socket,address=8787,server=y,suspend=n
````
应该是IBM的安全策略限制问题导致的，不知道有没有什么方法解决安全策略限制。

**Comment by muyuqiu001** [comment]
这个问题还需要继续跟踪，业务在使用的时候肯定不同意加上debug参数的，需要看看还有没有其他解决方式.

**Comment by oldmanpushcart** [comment]
这个帮忙一起看了，春节的时间已经确定要做GREYS1.8版本开发，估计没空跟着 :)

**Comment by oldmanpushcart** [comment]
有进展么，同学

**Comment by muyuqiu001** [comment]
@oldmanpushcart 最近没搞这个了，就没有跟着。。要不先关了吧

**Comment by atonce** [comment]
我这边发现在was的启动参数配置了这个后就可以正常使用trace tt 等命令,不在报上面的错误
-Dwas.debug.mode=true
