### ISSUE TITLE
GREYS启动失败

### ISSUE THREAD

**Issue by oldmanpushcart** [oldmanpushcart/greys-anatomy#140]
```
java.lang.IllegalAccessError: tried to access class com.github.ompc.greys.agent.AgentLauncher$1 from class com.github.ompc.greys.agent.AgentLauncher
    at com.github.ompc.greys.agent.AgentLauncher.loadOrDefineClassLoader(AgentLauncher.java:45)
    at com.github.ompc.greys.agent.AgentLauncher.main(AgentLauncher.java:128)
    at com.github.ompc.greys.agent.AgentLauncher.agentmain(AgentLauncher.java:22)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
    at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:411)
```

**Comment by oldmanpushcart** [comment]
在`1.7.6.4`中修复

**Comment by oldmanpushcart** [comment]
在`1.7.6.4`中修复

**Comment by oldmanpushcart** [comment]
在`1.7.6.4`中修复
