### ISSUE TITLE
Exception in thread "main" java.net.ConnectException: Connection refused

### ISSUE THREAD

**Issue by Dyrcj** [oldmanpushcart/greys-anatomy#161]
使用./greys.sh运行时抛出异常
``` java
Exception in thread "main" java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.github.ompc.greys.core.GreysConsole.connect(GreysConsole.java:181)
	at com.github.ompc.greys.core.GreysConsole.<init>(GreysConsole.java:68)
	at com.github.ompc.greys.core.GreysConsole.main(GreysConsole.java:299)
active console failed.
```
然后目标程序抛出的异常是
``` java
objc[37704]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/bin/java (0x10428e4c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x10d22d4e0). One of the two will be used. Which one is undefined.
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "createClassLoader")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.security.AccessController.checkPermission(AccessController.java:884)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at java.lang.SecurityManager.checkCreateClassLoader(SecurityManager.java:611)
	at java.lang.ClassLoader.checkCreateClassLoader(ClassLoader.java:274)
	at java.lang.ClassLoader.<init>(ClassLoader.java:335)
	at java.security.SecureClassLoader.<init>(SecureClassLoader.java:99)
	at java.net.URLClassLoader.<init>(URLClassLoader.java:144)
	at com.github.ompc.greys.agent.AgentClassLoader.<init>(AgentClassLoader.java:15)
	at com.github.ompc.greys.agent.AgentLauncher.loadOrDefineClassLoader(AgentLauncher.java:43)
	at com.github.ompc.greys.agent.AgentLauncher.main(AgentLauncher.java:106)
	at com.github.ompc.greys.agent.AgentLauncher.agentmain(AgentLauncher.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:411)

```

**Comment by oldmanpushcart** [comment]
这个看起来似乎是因为你的`java.policy`禁止了`createClassLoader`的权限，需要核对并打开。 具体怎么核对和修改，可以Google下哈
