### ISSUE TITLE
执行 shutdown 以后，无法再连接

### ISSUE THREAD

**Issue by cyberdak** [oldmanpushcart/greys-anatomy#162]
这是目标jvm打印的日志

```
[12-09 13:07:08 558 ERROR] [Attach Listener] log.SystemPrintStream - SLF4J: Class path contains multiple SLF4J bindings.
[12-09 13:07:08 559 ERROR] [Attach Listener] log.SystemPrintStream - SLF4J: Found binding in [jar:file:/opt/scf/service/lib/slf4j-log4j12-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[12-09 13:07:08 559 ERROR] [Attach Listener] log.SystemPrintStream - SLF4J: Found binding in [jar:file:/root/.greys/lib/1.7.6.4/greys/greys-core.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[12-09 13:07:08 559 ERROR] [Attach Listener] log.SystemPrintStream - SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
[12-09 13:07:08 605 ERROR] [Attach Listener] log.SystemPrintStream - SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
[12-09 13:07:08 669 ERROR] [Attach Listener] log.SystemPrintStream - java.lang.reflect.InvocationTargetException
[12-09 13:07:08 669 ERROR] [Attach Listener] log.SystemPrintStream -    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12-09 13:07:08 669 ERROR] [Attach Listener] log.SystemPrintStream -    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[12-09 13:07:08 669 ERROR] [Attach Listener] log.SystemPrintStream -    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[12-09 13:07:08 669 ERROR] [Attach Listener] log.SystemPrintStream -    at java.lang.reflect.Method.invoke(Method.java:597)
[12-09 13:07:08 669 ERROR] [Attach Listener] log.SystemPrintStream -    at com.github.ompc.greys.agent.AgentLauncher.main(AgentLauncher.java:131)
[12-09 13:07:08 669 ERROR] [Attach Listener] log.SystemPrintStream -    at com.github.ompc.greys.agent.AgentLauncher.agentmain(AgentLauncher.java:20)
[12-09 13:07:08 669 ERROR] [Attach Listener] log.SystemPrintStream -    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12-09 13:07:08 670 ERROR] [Attach Listener] log.SystemPrintStream -    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[12-09 13:07:08 670 ERROR] [Attach Listener] log.SystemPrintStream -    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[12-09 13:07:08 670 ERROR] [Attach Listener] log.SystemPrintStream -    at java.lang.reflect.Method.invoke(Method.java:597)
[12-09 13:07:08 670 ERROR] [Attach Listener] log.SystemPrintStream -    at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:323)
[12-09 13:07:08 670 ERROR] [Attach Listener] log.SystemPrintStream -    at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:348)
[12-09 13:07:08 670 ERROR] [Attach Listener] log.SystemPrintStream - Caused by: java.net.BindException: Address already in use
[12-09 13:07:08 670 ERROR] [Attach Listener] log.SystemPrintStream -    at sun.nio.ch.Net.bind(Native Method)
[12-09 13:07:08 670 ERROR] [Attach Listener] log.SystemPrintStream -    at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:124)
[12-09 13:07:08 670 ERROR] [Attach Listener] log.SystemPrintStream -    at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:59)
[12-09 13:07:08 670 ERROR] [Attach Listener] log.SystemPrintStream -    at com.github.ompc.greys.core.server.GaServer.bind(GaServer.java:200)
[12-09 13:07:08 670 ERROR] [Attach Listener] log.SystemPrintStream -    ... 12 more
[12-09 13:08:21 471 ERROR] [ga-selector-daemon] log.SystemPrintStream - Exception in thread "ga-selector-daemon" 
[12-09 13:08:21 472 ERROR] [ga-selector-daemon] log.SystemPrintStream - java.util.concurrent.RejectedExecutionException
[12-09 13:08:21 472 ERROR] [ga-selector-daemon] log.SystemPrintStream -         at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:1774)
[12-09 13:08:21 472 ERROR] [ga-selector-daemon] log.SystemPrintStream -         at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:768)
[12-09 13:08:21 472 ERROR] [ga-selector-daemon] log.SystemPrintStream -         at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:656)
[12-09 13:08:21 472 ERROR] [ga-selector-daemon] log.SystemPrintStream -         at com.github.ompc.greys.core.server.GaServer.doRead(GaServer.java:354)
[12-09 13:08:21 472 ERROR] [ga-selector-daemon] log.SystemPrintStream -         at com.github.ompc.greys.core.server.GaServer.access$200(GaServer.java:105)
[12-09 13:08:21 472 ERROR] [ga-selector-daemon] log.SystemPrintStream -         at com.github.ompc.greys.core.server.GaServer$4.run(GaServer.java:255)

```

再次使用 `./greys.sh pid` ，会卡住，当使用 Ctrl+z 取消时，显示 `active console failed.`

目标JVM是6u45，greys版本是自动更新的最新版。

我现在的疑问是，是不是我对shutdown的理解有错误？

**Comment by oldmanpushcart** [comment]
从日志上看，是3658端口被占用了，`shutdown`命令执行之后，端口3658会被释放掉才对。可以用netstat命令看看3658端口被那个应用占了。

shutdown命令执行的语义：退出所有字节码增强的类，释放掉所有greys占用的资源（线程、端口）

**Comment by tcgdy0201** [comment]
@oldmanpushcart 参考你在 https://github.com/oldmanpushcart/greys-anatomy/issues/163 中回复的解决方案，shutdown不能，再次执行`./greys.sh pid`也碰到了同样的问题。

**Comment by oldmanpushcart** [comment]
刚刚留意到一个细节，你是用`CTRL+Z`结束的么？但这个指令是向目标进程发起的是挂起后台，用`fg`命令可以恢复。

```
ctrl+c和ctrl+z都是中断命令,但是他们的作用却不一样.
ctrl+c是强制中断程序的执行,
而ctrl+z的是将任务中断,但是此任务并没有结束,他仍然在进程中他只是维持挂起的状态,用户可以使用fg/bg操作继续前台或后台的任务,fg命令重新启动前台被中断的任务,bg命令把被中断的任务放在后台执行.
例如:
```
