### ISSUE TITLE
启动时报拒绝链接异常

### ISSUE THREAD

**Issue by l1xiao** [oldmanpushcart/greys-anatomy#191]
尝试在生产环境使用，但是启动的时候报了如下异常。使用的是Java8，CentOS6，请问该如何解决这个问题呢？
[user@host greys]$ ./greys.sh 2857@127.0.0.1:8081
Exception in thread "main" java.net.ConnectException: 拒绝连接
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
        at com.github.ompc.greys.core.GreysConsole.connect(GreysConsole.java:181)
        at com.github.ompc.greys.core.GreysConsole.<init>(GreysConsole.java:68)
        at com.github.ompc.greys.core.GreysConsole.main(GreysConsole.java:299)

**Comment by oldmanpushcart** [comment]
`8081`端口比较特殊，TOMCAT很喜欢使用，我不确定这个端口是否已经被占用了。尝试用

```
./greys.sh 2587
```

能否访问呢？

**Comment by l1xiao** [comment]
感谢你的回复，确实是这个问题

**Comment by EdwardLee03** [comment]
脚本如果能检测到端口被占用并提示，岂不是更好。 @oldmanpushcart

**Comment by oldmanpushcart** [comment]
其实是可以的，我在新的内核中也实现了这个解决方案。能做到用户不需要感知到JVM进程号和端口号的绑定关系。

但苦于没有时间去把功能在GREYS老版本上也重新实现一次，所以，先忍着。

**Comment by EdwardLee03** [comment]
辛苦，excellent 👍
