### ISSUE TITLE
最新的greys-1.7.6.5-bin.zip 是用jdk9编译的把？java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer

### ISSUE THREAD

**Issue by zhaiyuyong** [oldmanpushcart/greys-anatomy#219]
最新的greys-1.7.6.5-bin.zip 是用jdk9编译的把？
好奇怪，之前好的突然就这样了，改java path也不行 

```java
2017-12-08T16:53:47.788+0800	INFO	ga-selector-daemon	stdout	2017-12-08 16:53:47 [ga-selector-daemon] INFO  greys-anatomy - accept new connection, client=java.nio.channels.SocketChannel[connected local=/127.0.0.1:3658 remote=/127.0.0.1:48470]@session[0]

2017-12-08T16:53:47.788+0800	INFO	ga-selector-daemon	stderr	Exception in thread "ga-selector-daemon" 
2017-12-08T16:53:47.788+0800	INFO	ga-selector-daemon	stderr	java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
2017-12-08T16:53:47.789+0800	INFO	ga-selector-daemon	stderr		at com.github.ompc.greys.core.server.GaServer.doRead(GaServer.java:324)
2017-12-08T16:53:47.789+0800	INFO	ga-selector-daemon	stderr		at com.github.ompc.greys.core.server.GaServer.access$200(GaServer.java:105)
2017-12-08T16:53:47.789+0800	INFO	ga-selector-daemon	stderr		at com.github.ompc.greys.core.server.GaServer$4.run(GaServer.java:255)
2017-12-08T16:58:47.983+0800	INFO	ga-session-expire-daemon	stdout	2017-12-08 16:58:47 [ga-session-expire-daemon] INFO  greys-anatomy - session[0] was expired

2017-12-08T16:58:47.986+0800	INFO	ga-session-expire-daemon	stdout	2017-12-08 16:58:47 [ga-session-expire-daemon] INFO  greys-anatomy - session[0] destroyed.

**Comment by zhaiyuyong** [comment]
https://github.com/plasma-umass/doppio/issues/497
This problem also happens when you build the software with JDK 9 with target JDK 8, because in JDK9 ByteBuffer.flip() returns a ByteBuffer... It used to return a Buffer in JDK8.

And then you try to run this on JDK8 you get exactly this error.

Java-Workaround: Just cast your ByteBuffer to Buffer before calling flip()... i.e. ((Buffer)byteBuffer).flip(). Then you can compile your project with JDK9 and have it running on JDK8.

Note: This is not really related to this project, I only use pure java. But I found this problem report and thought you might be interested in a workaround for this.

**Comment by oldmanpushcart** [comment]
非常抱歉，我立即解决！！

**Comment by oldmanpushcart** [comment]
搞定了

**Comment by zhaiyuyong** [comment]
那个pom只能指定编译出来的class文件
minor version: 0
major version: 50
但是如果用了jdk9对比jdk8变化了的api还是有问题
