### ISSUE TITLE
Elasticsearch 为什么不能观察呢

### ISSUE THREAD

**Issue by whitelilis** [oldmanpushcart/greys-anatomy#230]
![image](https://user-images.githubusercontent.com/1090230/34857688-32c7ce4c-f787-11e7-9b70-062e0bee3d86.png)

如上图，不明觉厉

**Comment by whitelilis** [comment]
找到程序的 out 日志中有如下东东
```
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "createClassLoader")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
        at java.security.AccessController.checkPermission(AccessController.java:884)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
        at java.lang.SecurityManager.checkCreateClassLoader(SecurityManager.java:611)
        at java.lang.ClassLoader.checkCreateClassLoader(ClassLoader.java:274)
        at java.lang.ClassLoader.<init>(ClassLoader.java:335)
        at java.security.SecureClassLoader.<init>(SecureClassLoader.java:99)
        at java.net.URLClassLoader.<init>(URLClassLoader.java:144)
        at com.github.ompc.greys.agent.AgentClassLoader.<init>(AgentClassLoader.java:15)
        at com.github.ompc.greys.agent.AgentLauncher.loadOrDefineClassLoader(AgentLauncher.java:43)
        at com.github.ompc.greys.agent.AgentLauncher.main(AgentLauncher.java:106)
        at com.github.ompc.greys.agent.AgentLauncher.agentmain(AgentLauncher.java:20)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:411)
```

**Comment by whitelilis** [comment]
在它的 policy 文件中打开各种限制
```
permission java.lang.RuntimePermission "createClassLoader";
  permission java.lang.RuntimePermission "shutdownHooks";
  permission java.io.FilePermission "～/.greys/lib/1.7.6.6/greys/greys-core.jar", "read";
```
报下面的错：
```
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.github.ompc.greys.agent.AgentLauncher.main(AgentLauncher.java:131)
        at com.github.ompc.greys.agent.AgentLauncher.agentmain(AgentLauncher.java:20)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:411)
Caused by: java.lang.IllegalArgumentException: hostname can't be null
        at java.net.InetSocketAddress.checkHost(InetSocketAddress.java:149)
        at java.net.InetSocketAddress.<init>(InetSocketAddress.java:216)
        at com.github.ompc.greys.core.server.GaServer.getInetSocketAddress(GaServer.java:223)
        at com.github.ompc.greys.core.server.GaServer.bind(GaServer.java:200)
        ... 12 more
```

**Comment by whitelilis** [comment]
可以排除是机器配置或环境的问题，因为 greys 其它 java 进程是可以的。只有 ES 的不行。

**Comment by oldmanpushcart** [comment]
```java
Caused by: java.lang.IllegalArgumentException: hostname can't be null
        at java.net.InetSocketAddress.checkHost(InetSocketAddress.java:149)
        at java.net.InetSocketAddress.<init>(InetSocketAddress.java:216)
        at com.github.ompc.greys.core.server.GaServer.getInetSocketAddress(GaServer.java:223)
        at com.github.ompc.greys.core.server.GaServer.bind(GaServer.java:200)
        ... 12 more
```

问题出在这里，说明`greys.sh`在attach的时候传递给JVM的参数中，`TARGET_IP`参数为空...不应该啊，而且只在Elasticsearch中出现这个问题，百思不得其解。

能否帮个小忙，在`greys.sh`中debug下，看在这个脚本中的`attach_jvm`方法相关的参数到底是怎样的？

```bash
# attach greys to target jvm
# $1 : greys_local_version
attach_jvm()
{
    local greys_lib_dir=${GREYS_LIB_DIR}/${1}/greys

    # if [ ${TARGET_IP} = ${DEFAULT_TARGET_IP} ]; then
    if [ ! -z ${TARGET_PID} ]; then
        ${JAVA_HOME}/bin/java \
            ${BOOT_CLASSPATH} ${JVM_OPTS} \
            -jar ${greys_lib_dir}/greys-core.jar \
                -pid ${TARGET_PID} \
                -target ${TARGET_IP}":"${TARGET_PORT} \
                -core "${greys_lib_dir}/greys-core.jar" \
                -agent "${greys_lib_dir}/greys-agent.jar"
    fi
}
```

**Comment by oldmanpushcart** [comment]
在主日志中也帮忙找下这条日志的输出（如果你的Elasticsearch默认开了INFO级的日志的话），应该在Elasticsearch的主日志中能找到。

```java
/**
 * GaServer操作的附件
 * Created by oldmanpushcart@gmail.com on 15/5/3.
 */
class GaAttachment {

    // ...以下省略千言万语

    /**
     * 启动Greys服务端
     *
     * @param configure 配置信息
     * @throws IOException 服务器启动失败
     */
    public void bind(Configure configure) throws IOException {
       
            // ...以下省略千言万语

            logger.info("ga-server listening on network={};port={};timeout={};", configure.getTargetIp(),
                    configure.getTargetPort(),
                    configure.getConnectTimeout());

            // ...以下省略千言万语

    }

    // ...以下省略千言万语

}
```

我想看`network`和`port`这两个参数的值

**Comment by whitelilis** [comment]
醉了。。。。。今天再测试，居然可以用了。。。。

**Comment by whitelilis** [comment]
另外， greys.sh 里执行的参数如下：
-target 127.0.0.1:9999

**Comment by whitelilis** [comment]
![image](https://user-images.githubusercontent.com/1090230/34935564-444500b0-fa19-11e7-9b14-2211818afffc.png)

**Comment by oldmanpushcart** [comment]
收到...我擦，为啥Configure.toString()竟然也被AccessControl拦住了...百撕不得骑姐
