### ISSUE TITLE
trace命令在处理大方法时会出现编译错误

### ISSUE THREAD

**Issue by oldmanpushcart** [oldmanpushcart/greys-anatomy#74]
```
2015-09-30 11:26:28 [ga-command-execute-daemon] WARN  greys-anatomy - transform loader[com.taobao.tomcat.container.context.loader.AliWebappClassLoader]:class[com/taobao/wmpinput/refund/service/RefundQualityChecking] failed.
java.lang.RuntimeException: Method code too large!
	at org.objectweb.asm.MethodWriter.a(Unknown Source) ~[greys-core.jar:na]
	at org.objectweb.asm.ClassWriter.toByteArray(Unknown Source) ~[greys-core.jar:na]
	at com.github.ompc.greys.core.advisor.Enhancer.transform(Enhancer.java:230) [greys-core.jar:na]
	at sun.instrument.TransformerManager.transform(TransformerManager.java:169) [na:1.6.0_32]
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:365) [na:1.6.0_32]
	at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method) [na:1.6.0_32]
	at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:124) [na:1.6.0_32]
	at com.github.ompc.greys.core.advisor.Enhancer.enhance(Enhancer.java:372) [greys-core.jar:na]
	at com.github.ompc.greys.core.server.DefaultCommandHandler.execute(DefaultCommandHandler.java:223) [greys-core.jar:na]
	at com.github.ompc.greys.core.server.DefaultCommandHandler.executeCommand(DefaultCommandHandler.java:87) [greys-core.jar:na]
	at com.github.ompc.greys.core.server.GaServer$4.run(GaServer.java:329) [greys-core.jar:na]
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886) [na:1.6.0_32]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908) [na:1.6.0_32]
	at java.lang.Thread.run(Thread.java:662) [na:1.6.0_32]
```

就其原因，主要还是`trace`命令要在每个方法中埋点过多，遇到大方法的时候非常容易超过JVM对于method_code不能超过64K的限制

**Comment by oldmanpushcart** [comment]
采用`ptrace`代替
